### PR TITLE
Duplicate Payload logging configuration

### PR DESCRIPTION
**Pull request by jprincipe**
The logging for the duplicate payload is now configurable

### CODE REVIEW

**Comment by mhenrixon** [comment]
Thats awesome and many thanks for the pull request! Would it be too much to also ask for a job specific configuration?

**Comment by jprincipe** [comment]
interesting idea.  I'll look to see what I can do

**Comment by jprincipe** [comment]
@mhenrixon the logging configuration is now available on a per worker basis

**Comment by mhenrixon** [comment]
Awesome! I'll get this released tonight!

**Pull request merged**
