### PR TITLE
fix: Sidekiq 7.2 throws TypeError: Unsupported command argument type: TrueClass when using byscore: true 

### PR DESCRIPTION
**Pull request by Amnesthesia**
According to [Sidekiq 7.2 changelog](https://github.com/sidekiq/sidekiq/blob/main/Changes.md#720), using `byscore: true` and `nx: true` will now throw, which causes Sidekiq not to start up anymore when using `sidekiq-unique-jobs`

### CODE REVIEW

**Comment by kwent** [comment]
Much needed ! Can we cut a new release with this patch ?

**Comment by Amnesthesia** [comment]
> Much needed ! Can we cut a new release with this patch ?

Hope so, fixed linting and specs but workflow requires approval — hoping it's green now 🤞

**Comment by Amnesthesia** [comment]
Any way you can approve workflow runs to run for the rest of the PR rather than for each commit? Doesn't it defeat the purpose of turning on auto-merge, if merge depends on workflows and workflows wont run without approval on each push?

**Comment by mhenrixon** [comment]
> Any way you can approve workflow runs to run for the rest of the PR rather than for each commit? Doesn't it defeat the purpose of turning on auto-merge, if merge depends on workflows and workflows wont run without approval on each push?

I don't even care to approve. I need to check the settings. This is absolutely ridiculous. 

Also, I will remove reek. It seems a little overkill to be honest.

**Pull request merged**
