### PR TITLE
fix: `while_executing` should not invoke conflict strategy when the job was successfully executed.

### PR DESCRIPTION
**Pull request by leandrogoe**
Currently, the `WhileExecuting` lock only works properly if the middleware chain downstream returns a truthy value.

When a falsey value is returned, the on-conflict strategy is invoked, which shouldn't happen.

Originally reported [here](https://github.com/mhenrixon/sidekiq-unique-jobs/issues/800).

### CODE REVIEW

**Review by mhenrixon — APPROVED** [review]

**Comment by leandrogoe** [comment]
There were some linting failures unrelated with the files I've touched, not sure why. I've corrected those as well now to make sure the pipeline passes.

**Comment by sfavrinlumint** [comment]
Hi @mhenrixon and @leandrogoe , was this fix supposed to go to the `v7.1` branch? Because the bug is present in the current release `8.0.3` and this PR fixes it.

**Comment by leandrogoe** [comment]
@sfavrinlumint I made it for the 7.1 because I was using 7.1.30 and hence needed a fix in that branch. Another PR will be needed for 8.X

**Comment by sfavrinlumint** [comment]
> @sfavrinlumint I made it for the 7.1 because I was using 7.1.30 and hence needed a fix in that branch. Another PR will be needed for 8.X

Ah silly me, gotcha thank you Leandro! I might open a PR for 8.0.3

**Comment by RobsonKing** [comment]
Are there plans to publish a release for this fix?

**Pull request merged**
