### PR TITLE
Add 'Delete All' button to web UI

### PR DESCRIPTION
**Pull request by john-denisov**
Close https://github.com/mhenrixon/sidekiq-unique-jobs/issues/357

I had to to put delete_all action above show action so it would get matched first.
I could have put it as last action if I used HTTP method POST instead of GET. But I assume that there's a reason why POST is not used for regular `delete` form. So I followed the same approach.
  Or we can leave it like that. Maybe it's just me who is used to order all actions by where they belong in `CRUD` acronym 😅

### CODE REVIEW

**Comment by john-denisov** [comment]
> Method registered has 26 lines of code (exceeds 25 allowed). Consider refactoring

Can somebody silence this CodeClimate error? 🙂

**Comment by john-denisov** [comment]
@mhenrixon added integration test for `/unique_digests/delete_all` endpoint

**Comment by mhenrixon** [comment]
Thanks @john-denisov, I fixed the style violations in #370 and will merge that as soon as the build passes.

**Comment by mhenrixon** [comment]
Closed with #370

**Pull request closed without merging**
