### PR TITLE
fix(digest): write digest on middleware call

### LINKED ISSUE #766: Jobs queued during existing job inherit lock digest
**Describe the bug**
JobA calls `JobB.perform_async`
JobB gets a lock digest in the job hash - [because the lock digest exists the middleware doesn't create a new lock digest,etc](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/main/lib/sidekiq_unique_jobs/middleware.rb#L38) and things don't go well.

**Expected behavior**
unique lock digests per job/args combo

**Current behavior**
Jobs chain the same lock digest. I don't think this happens 100% of the time but it's frequent. 

sidekiq-unique-jobs 8.0.2
sidekiq 7.0.7

couple of ways to show this off, below is with another middleware, monkey patching the middleware with a log before the lock digest check also shows the same

```ruby
class LogClient
  include Sidekiq::ClientMiddleware

  def call(_worker, job, _queue, _redis_pool)
    Rails.logger.info "LogClient: #{job['lock_digest']} || #{job['jid']}" if job['lock_digest'].present?
    yield
  end
end

Sidekiq.configure_server do |config|
  config.queues = %w[list]
  config.concurrency = 20

  config.capsule('limited') do |cap|
    cap.concurrency = 8
    cap.queues = %w[special]
  end

  config.client_middleware do |chain|
    chain.add LogClient
    chain.add SidekiqUniqueJobs::Middleware::Client
  end

  config.server_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Server
  end

  SidekiqUniqueJobs::Server.configure(config)
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add LogClient
    chain.add SidekiqUniqueJobs::Middleware::Client
  end
end

class ItemCreateJob < ApplicationWorker
  sidekiq_options lock: :until_and_while_executing
  def perform
    UserItemCreateJob.perform_async 1
  end
end

class UserItemCreateJob< ApplicationWorker
  sidekiq_options lock: :until_and_while_executing
  def perform(user_id)
    logger.error user_id
  end
end
```

irb
```ruby
ItemCreateJob.perform_async
=> "381d4388288ab468ba5a8e2a "
```

logs (issue doesn't occur for job that comes out of irb/outside of sidekiq - just on the sidekiq server side
```ruby
2023-03-23T03:28:09.751Z pid=1608050 tid=10bee class=ItemCreateJob jid=381d4388288ab468ba5a8e2a INFO: start
2023-03-23T03:28:09.752Z pid=1608050 tid=10bee class=ItemCreateJob jid=381d4388288ab468ba5a8e2a INFO: [UNIQUE] before prepare item prod_uniq:22616be5af91c8e73845991af942d8f8

2023-03-23T03:29:43.843Z pid=1608050 tid=10bbq INFO: LogClient: prod_uniq:22616be5af91c8e73845991af942d8f8 || 0b258bc2c01990c7dc9ebec9
```

in prod we also see lock digests coming off of jobs to other jobs that don't have themselves have lock methods themselves (JobA has no `lock` but JobB does, I haven't nailed down where they are coming from but it's possible JobC calls JobA and JobC has a `lock`

raw prod debug logs with just the job names changed - note jid & job class change but lock_digest stays the same. WorkerA has no log args, WorkerB is a basic `lock: :until_and_while_executing`

```
Mar 22 20:02:37 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:37.636Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] soft Deleting lock for prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:37 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:37.708Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] lock! prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:37 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:37.708Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] locked? prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:37 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:37.708Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] taken? prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:38 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:37.742Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] enqueue prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:38 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:38.068Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] write_lock_info prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:38 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:38.245Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] primed_sync prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:38 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:38.266Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] pop_queued prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:38 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:38.271Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] rpoplpush prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:39 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:38.276Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] handle_primed prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:02:39 ip-172-31-11-45 sidekiq:   2023-03-22T20:02:39.068Z pid=28526 tid=1p6y class=WorkerA   jid=b2a6c29d05fb39da586c4b6f uniquejobs=client   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   UNIQUE_LOG_WATCH locked for WorkerB args [1493] lock   prod_uniq:3a2c7382851c8df6787efd946aabda18 jid 1032cd10e20bcf5e814d0749
Mar 22 20:09:07 ip-172-31-4-102 sidekiq:   2023-03-22T20:09:07.949Z pid=12932 tid=1z60 class=WorkerB   jid=1032cd10e20bcf5e814d0749 INFO: start
Mar 22 20:09:07 ip-172-31-4-102 sidekiq:   2023-03-22T20:09:07.966Z pid=12932 tid=1z60 class=WorkerB   jid=1032cd10e20bcf5e814d0749 uniquejobs=server   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] unlock prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:09:07 ip-172-31-4-102 sidekiq:   2023-03-22T20:09:07.966Z pid=12932 tid=1z60 class=WorkerB   jid=1032cd10e20bcf5e814d0749 uniquejobs=server   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] locked? prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:09:07 ip-172-31-4-102 sidekiq:   2023-03-22T20:09:07.966Z pid=12932 tid=1z60 class=WorkerB   jid=1032cd10e20bcf5e814d0749 uniquejobs=server   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   [UNIQUE] taken? prod_uniq:3a2c7382851c8df6787efd946aabda18   1032cd10e20bcf5e814d0749
Mar 22 20:09:07 ip-172-31-4-102 sidekiq:   2023-03-22T20:09:07.971Z pid=12932 tid=1z60 class=WorkerB   jid=1032cd10e20bcf5e814d0749 uniquejobs=server   until_and_while_executing=prod_uniq:3a2c7382851c8df6787efd946aabda18 INFO:   UNIQUE_LOG_WATCH unlock_failed for WorkerB args [1493] lock   prod_uniq:3a2c7382851c8df6787efd946aabda18 jid 1032cd10e20bcf5e814d0749
Mar 22 20:09:07 ip-172-31-4-102 sidekiq:   2023-03-22T20:09:07.973Z pid=12932 tid=1z60 class=WorkerB   jid=1032cd10e20bcf5e814d0749 elapsed=0.025 INFO: done
```

any ideas or pointers on where to look would be much appreciated

### PR DESCRIPTION
**Pull request by mhenrixon**
Closes #766 

@JeremiahChurch can you check if this solves your problem?

### CODE REVIEW

**Comment by JeremiahChurch** [comment]
Apologies for the delayed response.

Local shake down of this has been positive. I'm going to get it in to our production this week - should know within a few hours if it solves our problems or not. Really appreciate the work on it! <3

**Comment by JeremiahChurch** [comment]
quick follow up - went in to prod today with the few recent changes on main ([here](https://github.com/JeremiahChurch/sidekiq-unique-jobs/tree/fix/write-digest-on-middleware-call)). Unusual issue required it come right back out, unfortunately. 

Only one or two workers were starting on each box (concurrency of 25 + ~15 more in capsules)

I'll pull the log details tomorrow and provide as well as look for what may have caused it.

**Comment by JeremiahChurch** [comment]
Apologies for the massive delay on this.

We've been running this fix against the top of main for the last ~month and it has greatly improved our processing.

I haven't found a single overlapping/duplicate unique key for different jobs - I'd call this a good fix!

This fix has 10+ fold increased #821 reoccurrence as we're generating so many additional keys.

**Comment by mhenrixon** [comment]
> This fix has 10+ fold increased #821 reoccurrence as we're generating so many additional keys.

Alright, I will release this after fixing the number of keys in the digests set.

**Comment by mhenrixon** [comment]
@JeremiahChurch I believe that the last commit [cddcc08](https://github.com/mhenrixon/sidekiq-unique-jobs/pull/774/commits/cddcc08e75661ee1f9947de28f337666fa292b07) will help you. There was potential for lingering keys in the original if statement.

**Pull request merged**
